name: rask

services:
  rask:
    image: rask:dev
    container_name: rask-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    ports:
      - 3000:3000
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: development
    restart: no
    tty: true
